### PR TITLE
Classic compatibility

### PR DESCRIPTION
**Pull request by MisatoTremor**
### What does this implement/fix? Explain your changes ###

Implemented a compatibility layer for Classic vs. Retail WoW so it *should* work in both versions.

### Does this close any currently open issues? ###

/
### Any relevant logs, error output, etc? ###

/
### Any other comments? ###

Classic WoW needs compatible versions of:
- oUF, e.g. https://git.tukui.org/Tukz/Tukui/tree/Classic/Tukui/Libs/oUF. Dunno if this can be targeted in pkgmeta as I am not firm enough with it, yet
- Aurora

Available through Curse  / WoWI:
- Bartender4
- Grid2
- KuiNameplates
- Masque
- Raven Classic

I think I had to do minor fixes for PhanxChat, but have to check that again.

### CODE REVIEW

**Comment by MisatoTremor** [comment]
Rebased on the 2.1.0 release and fixed my added Clique skin for Retail WoW. So far it's working on Retail

**Comment by MisatoTremor** [comment]
Updated to 2.1.1 and fixed the compatRelease condition on 2 occasions where I don't even get how they worked before.

**Comment by Gethe** [comment]
the old compatRelease conditions worked because WoW reads each file, converts it into a function, then runs that function. Then, you're on `classic` it would hit 

``` lua
if not _G.WOW_PROJECT_ID == _G.WOW_PROJECT_MAINLINE then return end
```

and the function would end immediately due to the `return` keyword. No other code in that file would be run.

**Comment by Gethe** [comment]
So i've been going through the code, and I think it'll be much easier to read as well as maintain if classic remained on a separate branch. I'll use this as a starting point and build from there. I'll keep this PR open until it's ready for an official release.

Feel free to continue pushing changes, but be sure to `pull` before you do so.

**Pull request closed without merging**
