### PR TITLE
Compability fixes for WOW 9.1.5

### PR DESCRIPTION
**Pull request by arnvid**
### What does this implement/fix? Explain your changes ###
- Compability with 9.1.5
- Fixes to work with updated Aurora
- Fixes to work with new Grid2 v2

### CODE REVIEW

**Comment by Contagion21** [comment]
This PR getting any traction? 
I'd love to help by debugging privates but I'm not even sure how to get a deployable package short of copying over changes to my addons folder manually.

**Comment by arnvid** [comment]
@Contagion21 
> This PR getting any traction? I'd love to help by debugging privates but I'm not even sure how to get a deployable package short of copying over changes to my addons folder manually.

Ping me on Discord and I'll give you a working Addons folder

**Comment by arnvid** [comment]
@Gethe - this PR is running nicely for me and the testers - are some hard to reproduce ones from M+ but should be good for a beta or public release now.

**Comment by MisatoTremor** [comment]
As of now RealUI_Skins throws mutliple errors on a fresh install:
```
x1  RealUI_Skins-2.3.0\FrameXML\ColorPickerFrame.lua:129: hooksecurefunc(): ColorPickerFrame is not a function
Stack: [string "=[C]"]: in function 'hooksecurefunc'
[string "@RealUI_Skins-2.3.0\FrameXML\ColorPickerFrame.lua"]:129: in main chunk
[string "=[C]"]: in function 'LoadAddOn'
[string "@RealUI_Core-2.3.0\Init.lua"]:6: in main chunk
Time: 2021/12/09 08:48:15 Index: 1/16
Locals:
```

This is repeated for all `_G.hooksecurefunc` in RealUI_Skins and other References to Blizzard UI elements

Another example:
```
x1  RealUI_Core-2.3.0\Infobar\Bar.lua:36: attempt to call field 'GameTooltipTemplate' (a nil value)
Stack: [string "@RealUI_Core-2.3.0\Infobar\Bar.lua"]:36: in main chunk
Time: 2021/12/09 08:48:15 Index: 8/16
Locals:
_ = "RealUI_Core-2.3.0"
private =  {
    AddOns =  {}
    Profiles =  {}
    RealUI =  {}
    profileToLayout =  {}
    oUF =  {}
    layoutToProfile =  {}
}
LDB =  {
    attributestorage =  {}
    pairs = function @Masque\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:70
    NewDataObject = function @Masque\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:36
    callbacks =  {}
    ipairs = function @Masque\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:81
    RegisterCallback = function @RealUI_Bugs-2.3.0\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
    GetNameByDataObject = function @Masque\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:63
    GetDataObjectByName = function @Masque\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:59
    UnregisterCallback = function @RealUI_Bugs-2.3.0\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
    domt =  {}
    proxystorage =  {}
    DataObjectIterator = function @Masque\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:55
    namestorage =  {}
    UnregisterAllCallbacks = function @RealUI_Bugs-2.3.0\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
}
qTip =  {
    activeTooltips =  {}
    LabelPrototype =  {}
    tooltipHeap =  {}
    cellPrototype =  {}
    tableHeap =  {}
    providerMetatable =  {}
    timerHeap =  {}
    providerPrototype =  {}
    onReleaseHandlers =  {}
    LabelProvider =  {}
    tipMetatable =  {}
    frameHeap =  {}
    IterateTooltips = function @RealUI_Core-2.3.0\Libs\LibQTip-1.0\LibQTip-1.0.lua:167
    CreateCellProvider = function @RealUI_Core-2.3.0\Libs\LibQTip-1.0\LibQTip-1.0.lua:284
    layoutCleaner = <unnamed> {}
    tipPrototype =  {}
    IsAcquired = function @RealUI_Core-2.3.0\Libs\LibQTip-1.0\LibQTip-1.0.lua:159
    Release = function @RealUI_Core-2.3.0\Libs\LibQTip-1.0\LibQTip-1.0.lua:148
    Acquire = function @RealUI_Core-2.3.0\Libs\LibQTip-1.0\LibQTip-1.0.lua:123
    cellMetatable =  {}
    frameMetatable =  {}
}
Aurora =  {
    1 =  {}
    2 =  {}
    Profile =  {}
    Hook =  {}
    classIcons =  {}
    Skin =  {}
    Scale =  {}
    Color =  {}
    Util =  {}
    Base =  {}
}
Base =  {
    SetHighlight = function @RealUI_Skins-2.3.0\Aurora\Skin\deprecated.lua:14
    SetTexture = function @RealUI_Skins-2.3.0\Aurora\Skin\api.lua:214
    SetFont = function @RealUI_Skins-2.3.0\Aurora\Skin\api.lua:90
    IsTextureRegistered = function @RealUI_Skins-2.3.0\Aurora\Skin\api.lua:210
    SetBackdropColor = function @RealUI_Skins-2.3.0\Aurora\Skin\backdrop.lua:392
    SetBackdrop = function @RealUI_Skins-2.3.0\Aurora\Skin\backdrop.lua:385
    CropIcon = function @RealUI_Skins-2.3.0\Aurora\Skin\api.lua:78
    GetAddonSkins = function @RealUI_Skins-2.3.0\Aurora\Skin\api.lua:55
    AddSkin = function @RealUI_Skins-2.3.0\Aurora\Skin\api.lua:39
    CreateBackdrop = function @RealUI_Skins-2.3.0\Aurora\Skin\backdrop.lua:366
    RegisterTexture = function @RealUI_Skins-2.3.0\Aurora\Skin\api.lua:224
}
RealUI =  {
    SetDefaultModuleLibraries = function @Masque\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
    SetModuleEnabled = function @RealUI_Core-2.3.0\Core.lua:519
    Scale =  {}
    DeepCopy = function @RealUI_Core-2.3.0\Util.lua:420
    ToggleAddonPositionControl = function @RealUI_Core-2.3.0\Core\AddonControl.lua:306
    EnableModule = function @AddOn
```
It looks like the whole init is called too early, when those are not yet available.

**Comment by arnvid** [comment]
@MisatoTremor - does this happen from this PR? It does require latest beta of Aurora, latest PR of oUF  and everything setup as a developer environment. If you oing me on RealIUI discord ( Hanshi ) then I can help yousm set this up

**Comment by arnvid** [comment]
@Gethe  sync with main branch - validating and testing in wow now

**Comment by Gethe** [comment]
I consider this PR to be complete. Thank you for your contributions.

**Pull request closed without merging**
